services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=acuchat_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  web:
    build: ./webapp
    # Bu komut konteynerin kapanmasını engeller, böylece içine girip komut yazabiliriz.
    command: tail -f /dev/null
    volumes:
      - ./webapp:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:adminpass@db:5432/acuchat_db
    depends_on:
      - db
      - ollama

volumes:
  postgres_data:
  ollama_data: